baseURL = "https://pbuff.cc"
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "zh-CN"
rssLimit = 10
theme = "hugo-texify3"
title = "pbuff07"

[pagination]
pagerSize = 10

[taxonomies]
tags = "tags"
categories = "categories"

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "cats"
name = "Cats"
url = "/cats/"
weight = 3

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/pbuff07"
weight = 4

[[menu.main]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
weight = 5
